# Generated by Django 3.2.15 on 2022-09-02 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlredirect',
            old_name='counter',
            new_name='count',
        ),
    ]
